name: Build Chromium (Windows x64)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-chromium-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git C:\depot_tools
        echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        # Set env var to prevent depot_tools from auto-downloading an old VS version
        echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Fetch Chromium source code
      run: |
        echo "Fetching Chromium source code. This will take a long time..."
        # fetch will automatically create the src directory
        fetch --no-history --nohooks chromium

    - name: Sync gclient dependencies
      working-directory: ./src
      run: |
        echo "Syncing gclient dependencies. This will take a long time..."
        gclient sync

    - name: Generate build files (GN)
      working-directory: ./src
      run: |
        echo "Generating build files..."
        # is_debug=false: Create a Release build
        # symbol_level=0: Do not generate debug symbols
        # is_official_build=true: Enable official build optimizations
        # proprietary_codecs=true ffmpeg_branding="Chrome": Enable proprietary codecs (H.264/AAC)
        # chrome_pgo_phase=0: Disable PGO to prevent errors from missing profiles
        # In PowerShell, double quotes inside single quotes can be stripped. We use ""Chrome"" to ensure it's passed as a string.
        gn gen out/Default --args='is_debug=false symbol_level=0 is_official_build=true proprietary_codecs=true ffmpeg_branding=""Chrome"" chrome_pgo_phase=0'

    - name: Compile Chromium
      working-directory: ./src
      run: |
        echo "Compiling Chromium. This is the most time-consuming step..."
        autoninja -C out/Default chrome
    
    - name: Prepare package for release
      run: |
        echo "Creating README for the release..."
        $gn_args = "is_debug=false symbol_level=0 is_official_build=true proprietary_codecs=true ffmpeg_branding='Chrome' chrome_pgo_phase=0"
        $build_date = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss "UTC"')
        $readme_content = @"
        # Chromium Build

        - **Build Date:** $build_date
        - **Branch/Commit:** ${{ github.ref }} @ ${{ github.sha }}

        ## GN Arguments
        ```
        $gn_args
        ```
        "@
        $readme_content | Out-File -FilePath "README.md" -Encoding utf8

        echo "Compressing build output..."
        Compress-Archive -Path src/out/Default/* -DestinationPath "chromium-win64.zip"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: Build #${{ github.run_number }}
        files: |
          chromium-win64.zip