name: Build Chromium with MP3/Video Support

on:
  workflow_dispatch:

jobs:
  build-chromium:
    runs-on: windows-latest
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$pwd\\depot_tools" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

    - name: Sync Chromium source
      run: |
        mkdir Chromium_build
        cd Chromium_build
        Set-Content .gclient 'solutions = [{"name": "src", "url": "https://chromium.googlesource.com/chromium/src.git", "managed": False, "custom_deps": {}, "custom_vars": {}}]'
        gclient sync --nohooks --no-history

    - name: Generate build args and generate ninja files
      run: |
        cd Chromium_build\src
        $args = 'is_debug=false is_component_build=false use_static_crt=true ffmpeg_branding="Chrome" proprietary_codecs=true enable_platform_hevc=true enable_media_remoting=true use_custom_libcxx=false target_cpu="x64" treat_warnings_as_errors=false'
        gn gen out\Release --args="$args"

    - name: Build Chromium
      run: |
        cd Chromium_build\src
        autoninja -C out\Release chrome

    - name: Compress out/Release
      run: |
        cd Chromium_build\src\out
        Compress-Archive -Path Release -DestinationPath $env:RUNNER_TEMP\ChromiumBuild.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChromiumBuild
        path: ${{ runner.temp }}\ChromiumBuild.zip
