name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
    - name: Checkout (just to init workspace)
      uses: actions/checkout@v4

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$env:GITHUB_WORKSPACE\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Create build directory and sync Chromium
      run: |
        mkdir Chromium_build
        cd Chromium_build
        Set-Content -Path ".gclient" -Value @"
        solutions = [
          {
            "name": "src",
            "url": "https://chromium.googlesource.com/chromium/src.git",
            "managed": False,
            "custom_deps": {},
            "custom_vars": {}
          }
        ]
        "@
                gclient sync --nohooks
              shell: pwsh

            - name: Generate build args
              run: |
                cd Chromium_build/src
                $args = @"
        is_debug=false
        is_component_build=false
        use_static_crt=true
        ffmpeg_branding="Chrome"
        proprietary_codecs=true
        enable_platform_hevc=true
        enable_media_remoting=true
        use_custom_libcxx=false
        target_cpu="x64"
        treat_warnings_as_errors=false
        "@
        $args | Out-File -Encoding ASCII args.gn
        gn gen out\Release --args="`"`n$(Get-Content args.gn -Raw)`"`n"
      shell: pwsh

    - name: Build Chromium (minimal)
      run: |
        cd Chromium_build/src
        ninja -C out/Release chrome
      shell: pwsh

    - name: Compress entire out/Release folder
      run: |
        $source = "Chromium_build\src\out\Release\*"
        $output = "chromium_build.zip"
        Compress-Archive -Path $source -DestinationPath $output
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chromium_build
        path: chromium_build.zip
