name: Build Chromium Static CRT (Auto Release)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1234)'
        required: true
      release_name:
        description: 'Release name (e.g. Chromium Static Build)'
        required: true
jobs:
  build:
    runs-on: windows-latest

    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      shell: powershell
      run: |
        choco install python3 -y
        choco install git -y

    - name: Setup depot_tools
      shell: powershell
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $env:PATH += ";$PWD\depot_tools"
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Process")

    - name: Fetch Chromium source
      shell: powershell
      run: |
        mkdir Chromium_build
        cd Chromium_build
        echo 'solutions = [{"name": "src", "url": "https://chromium.googlesource.com/chromium/src.git", "managed": False, "custom_deps": {}, "custom_vars": {}}]' > .gclient
        gclient sync --nohooks

    - name: Configure Build Args
      shell: powershell
      run: |
        cd Chromium_build\src
        $args = @"
        is_debug=false
        is_component_build=false
        use_static_crt=true
        ffmpeg_branding="Chrome"
        proprietary_codecs=true
        enable_platform_hevc=true
        enable_media_remoting=true
        use_custom_libcxx=false
        target_cpu="x64"
        treat_warnings_as_errors=false
        "@
        $args | Out-File -Encoding ascii args.gn
        gn gen out\Release --args="`r`n$args`r`n"

    - name: Build Chromium
      shell: powershell
      run: |
        cd Chromium_build\src
        ninja -C out\Release chrome

    - name: Compress Build Output
      shell: powershell
      run: |
        cd Chromium_build\src\out
        Compress-Archive -Path .\Release\* -DestinationPath ..\..\..\chromium-release.zip

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: chromium-release
        path: chromium-release.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: chromium-release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
