name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Chromium
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depot_tools
      run: |
        git clone --progress https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $depotPath = "$PWD\depot_tools"
        Set-Item -Path Env:PATH -Value "$Env:PATH;$depotPath"
      shell: pwsh

    - name: Install build dependencies
      run: |
        cd chromium/src/build
        cmd /c ".\install-build-deps.bat"
      shell: pwsh

    - name: Install Ninja
      run: |
        choco install ninja -y
      shell: pwsh

    - name: Clone and Fetch Chromium source code
      run: |
        mkdir chromium
        cd chromium
        git clone --progress https://chromium.googlesource.com/chromium/src.git
        cd src
        fetch --nohooks --no-history --revision=3945 chromium/src
      shell: pwsh

    - name: Configure Chromium build
      run: |
        cd chromium/src
        gn gen out/Default --args="is_debug=false proprietary_codecs=true ffmpeg_branding=\"Chrome\""
      shell: pwsh

    - name: Build Chromium
      run: |
        cd chromium/src
        ninja -C out/Default chrome
