name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Chromium
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depot_tools
      run: |
        git clone --progress https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $depotPath = "$PWD\depot_tools"
        Set-Item -Path Env:PATH -Value "$Env:PATH;$depotPath"
      shell: pwsh

    - name: Create build directory
      run: |
        mkdir chromium\src\build
      shell: pwsh
    - name: Install build dependencies
      run: |
        # Download install-build-deps.py script
        curl -o install-build-deps.py https://chromium.googlesource.com/chromium/src/+/HEAD/build/install-build-deps.py?format=TEXT
        base64 -d install-build-deps.py > install-build-deps.py_decoded
        
        # Install build dependencies
        python install-build-deps.py_decoded
      shell: pwsh
