name: Build Chromium

on: [workflow_dispatch]

jobs:
  build:
    name: Build Chromium
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        set PATH=%PATH%;%cd%\depot_tools

    - name: Configure Chromium build
      run: |
        mkdir chromium
        cd chromium
        fetch --nohooks --no-history chromium
        cd src
        ./build/install-build-deps.bat

    - name: Build Chromium
      run: |
        cd chromium\src
        gn gen out/Default
        ninja -C out/Default chrome

    - name: Archive Chromium build
      uses: actions/upload-artifact@v2
      with:
        name: chromium-build
        path: chromium\src\out\Default
