name: Build Chromium Static CRT (Auto Release)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v1234)'
        required: true
      release_name:
        description: 'Release name (e.g. Chromium Static Build)'
        required: true

jobs:
  build:
    name: Chromium Static CRT Build
    runs-on: windows-2022

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      shell: powershell
      run: |
        choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools git python3 7zip
        git config --global core.autocrlf false

    - name: Set DEPOT_TOOLS_WIN_TOOLCHAIN=0
      shell: powershell
      run: |
        echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Clone depot_tools
      shell: powershell
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$pwd\\depot_tools" >> $env:GITHUB_PATH

    - name: Fetch Chromium source
      shell: powershell
      run: |
        mkdir chromium
        cd chromium
        fetch --nohooks chromium
        gclient runhooks

    - name: Configure build args (Static CRT + Audio/Video)
      shell: powershell
      run: |
        cd chromium\src
        $args = @"
        is_debug=false
        is_component_build=false
        use_static_crt=true
        ffmpeg_branding="Chrome"
        proprietary_codecs=true
        enable_platform_hevc=true
        enable_media_remoting=true
        use_custom_libcxx=false
        target_cpu="x64"
        treat_warnings_as_errors=false
        "@
        $args | Out-File -Encoding ASCII args.gn
        gn gen out\Release --args="`type args.gn`"

    - name: Build Chromium (Release Static CRT)
      shell: powershell
      run: |
        cd chromium\src
        ninja -C out\Release chrome

    - name: Archive Build Output
      shell: powershell
      run: |
        Compress-Archive -Path chromium\src\out\Release\* -DestinationPath chromium-staticcrt.zip

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        name: ${{ github.event.inputs.release_name }}
        body: "Automated build: static CRT, proprietary codecs (H.264, HEVC), no VC++ runtime needed."
        draft: false
        prerelease: false
        files: chromium-staticcrt.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
