name: Build Chromium

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Chromium
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depot_tools
      run: |
        git clone --progress https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $depotPath = "$PWD\depot_tools"
        Set-Item -Path Env:PATH -Value "$Env:PATH;$depotPath"
      shell: pwsh

    - name: Create build directory
      run: |
        mkdir chromium\src\build
      shell: pwsh
    - name: Install build dependencies
      run: |
        # Download install-build-deps.py script
        Invoke-WebRequest -Uri 'https://chromium.googlesource.com/chromium/src/+/HEAD/build/install-build-deps.py?format=TEXT' -OutFile 'install-build-deps.py'
        
        # Decode install-build-deps.py script
        [System.Convert]::FromBase64String((Get-Content 'install-build-deps.py' -Raw)) | Set-Content 'install-build-deps.py_decoded'
        
        # Install build dependencies
        python install-build-deps.py_decoded || exit 1
      shell: pwsh

