name: Build Chromium for Windows

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    name: Build Chromium
    runs-on: windows-2022  # 使用 Windows 2022 环境，依赖 Visual Studio

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      shell: powershell
      run: |
        choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools git python3 7zip
        git config --global core.autocrlf false

    - name: Clone depot_tools
      shell: powershell
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$pwd\\depot_tools" >> $env:GITHUB_PATH

    - name: Fetch Chromium source
      shell: powershell
      run: |
        mkdir chromium
        cd chromium
        fetch --nohooks chromium
        gclient runhooks

    - name: Configure build args (with audio/video support)
      shell: powershell
      run: |
        cd chromium\src
        $args = @"
        is_debug=false
        is_component_build=false
        ffmpeg_branding="Chrome"
        proprietary_codecs=true
        enable_platform_hevc=true
        enable_media_remoting=true
        target_cpu="x64"
        "@
        $args | Out-File -Encoding ASCII args.gn
        gn gen out\Release --args="`type args.gn`"

    - name: Build Chromium (Release)
      shell: powershell
      run: |
        cd chromium\src
        ninja -C out\Release chrome

    - name: Archive build output
      shell: powershell
      run: |
        Compress-Archive -Path chromium\src\out\Release\* -DestinationPath chromium-win.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chromium-win
        path: chromium-win.zip
